### ISSUE TITLE
Insert Task : Perlu checking format tanggal deadline task yang diinput user

### ISSUE THREAD

**Issue by ardhiesta** [ardhiesta/ToDoApp#5]
Tambahkan mekanisme untuk mengecek apakah tanggal deadline task sudah sesuai format YYYY-MM-DD

**Comment by alfikiafan** [comment]
public void insertTask(){
        Scanner scanner = new Scanner(System.in);
        // user diminta mengetik task yg akan dikerjakan
        System.out.print("Tulis tugas yang akan dikerjakan: ");
        String task = scanner.nextLine();

        // user diminta mengetik deadline task dalam format YYYY-MM-DD
        // TODO :
        // checking format deadline yang diinput user, kalau tidak sesuai diminta mengulangi
        while (true){
            System.out.print("Tuliskan deadline tugas (YYYY-MM-DD): ");
            String deadline = scanner.nextLine();
            String regex = "^((2000|2400|2800|(19|2[0-9])(0[48]|[2468][048]|[13579][26]))-02-29)$"
                    + "|^(((19|2[0-9])[0-9]{2})-02-(0[1-9]|1[0-9]|2[0-8]))$"
                    + "|^(((19|2[0-9])[0-9]{2})-(0[13578]|10|12)-(0[1-9]|[12][0-9]|3[01]))$"
                    + "|^(((19|2[0-9])[0-9]{2})-(0[469]|11)-(0[1-9]|[12][0-9]|30))$";
            Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(deadline);
            if (matcher.matches()) {
                saveData(task, deadline);
                break;
            }
            else {
                System.out.println("Format data belum benar");
            }
        }
        // panggil method untuk simpan data ke db
        scanner.close();
    }

**Comment by alfikiafan** [comment]
public void insertTask(){
        Scanner scanner = new Scanner(System.in);
        // user diminta mengetik task yg akan dikerjakan
        System.out.print("Tulis tugas yang akan dikerjakan: ");
        String task = scanner.nextLine();
        // user diminta mengetik deadline task dalam format YYYY-MM-DD
        // TODO :
        // checking format deadline yang diinput user, kalau tidak sesuai diminta mengulangi
        while (true){
            System.out.print("Tuliskan deadline tugas (YYYY-MM-DD): ");
            String deadline = scanner.nextLine();
            String regex = "^((2000|2400|2800|(19|2[0-9])(0[48]|[2468][048]|[13579][26]))-02-29)$"
                    + "|^(((19|2[0-9])[0-9]{2})-02-(0[1-9]|1[0-9]|2[0-8]))$"
                    + "|^(((19|2[0-9])[0-9]{2})-(0[13578]|10|12)-(0[1-9]|[12][0-9]|3[01]))$"
                    + "|^(((19|2[0-9])[0-9]{2})-(0[469]|11)-(0[1-9]|[12][0-9]|30))$";
            Pattern pattern = Pattern.compile(regex);
            Matcher matcher = pattern.matcher(deadline);
            if (matcher.matches()) {
                saveData(task, deadline);
                break;
            }
            else {
                System.out.println("Format data belum benar");
            }
        }
        // panggil method untuk simpan data ke db
        scanner.close();
    }

**Comment by ardhiesta** [comment]
Solved by Alfiki Diastama Afan Firdaus
https://github.com/ardhiesta/ToDoApp/commit/fb21884853051f6b813e644c09a5c493b0c1a074
